//! Golden tests for the backtest simulator (GAP-MAP P1 NEW).
//!
//! The fixtures under `tests/fixtures/backtest/` were generated by
//! `tools/gen_backtest_fixtures.py` — an INDEPENDENT Python implementation
//! of the same formulas `backtest::{fill_model, exit_sim}` uses, with the
//! expected outcomes stored next to each scenario. Every fixture carries
//! `"label": "synthetic"` at the top level and in its scenario; these
//! tests refuse to run on anything else.
//!
//! What this file proves:
//! 1. There are ≥ 50 fixtures, and every one is labelled synthetic.
//! 2. The Rust simulator reproduces the Python-computed outcomes within a
//!    tight tolerance, for fills, exits and per-trade PnL.
//! 3. `run_backtest` over the whole corpus is byte-deterministic and its
//!    report carries the synthetic label and the model caveats.

use std::path::PathBuf;

use serde_json::Value;

use module_sniper::backtest::dataset::DatasetLabel;
use module_sniper::backtest::exit_sim::{simulate_exit, ExitConfig};
use module_sniper::backtest::fill_model::{simulate_fill, FillModelConfig, FillOutcome};
use module_sniper::backtest::metrics::TradeRecord;
use module_sniper::backtest::{run_backtest, BacktestScenario};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/backtest")
}

fn load_fixtures() -> Vec<(String, Value)> {
    let dir = fixtures_dir();
    let mut entries: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("fixtures dir {dir:?} unreadable: {e}"))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    entries.sort(); // deterministic order by file name
    entries
        .into_iter()
        .map(|p| {
            let text = std::fs::read_to_string(&p).expect("fixture readable");
            let v: Value = serde_json::from_str(&text)
                .unwrap_or_else(|e| panic!("{}: invalid JSON: {e}", p.display()));
            (p.file_name().unwrap().to_string_lossy().into_owned(), v)
        })
        .collect()
}

/// Relative-difference tolerance for f64 cross-implementation checks.
fn close(got: f64, want: f64) -> bool {
    if want == 0.0 {
        return got.abs() < 1e-12;
    }
    ((got - want) / want).abs() < 1e-9
}

#[test]
fn corpus_has_at_least_fifty_synthetic_fixtures() {
    let fixtures = load_fixtures();
    assert!(
        fixtures.len() >= 50,
        "GAP-MAP requires ≥ 50 backtest fixtures, found {}",
        fixtures.len()
    );
    for (name, v) in &fixtures {
        assert_eq!(
            v["label"].as_str(),
            Some("synthetic"),
            "{name}: top-level label must be synthetic"
        );
        assert_eq!(
            v["scenario"]["label"].as_str(),
            Some("synthetic"),
            "{name}: scenario label must be synthetic"
        );
        let scenario: BacktestScenario = serde_json::from_value(v["scenario"].clone())
            .unwrap_or_else(|e| panic!("{name}: scenario parse: {e}"));
        assert_eq!(scenario.label, DatasetLabel::Synthetic);
        assert!(scenario.defects().is_empty(), "{name}: {:?}", scenario.defects());
    }
}

#[test]
fn rust_simulator_matches_the_python_reference_outcomes() {
    for (name, v) in load_fixtures() {
        let scenario: BacktestScenario =
            serde_json::from_value(v["scenario"].clone()).expect("scenario parses");
        let fill_cfg: FillModelConfig =
            serde_json::from_value(v["fill_config"].clone()).expect("fill config parses");
        let exit_cfg: ExitConfig =
            serde_json::from_value(v["exit_config"].clone()).expect("exit config parses");
        let expected = &v["expected"];

        match simulate_fill(&scenario, &fill_cfg) {
            FillOutcome::Rejected(reject) => {
                assert_eq!(
                    expected["executed"].as_bool(),
                    Some(false),
                    "{name}: python said filled, rust rejected"
                );
                assert_eq!(
                    expected["reject_reason"].as_str(),
                    Some(reject.as_str()),
                    "{name}: reject reason mismatch"
                );
            }
            FillOutcome::Filled(fill) => {
                assert_eq!(
                    expected["executed"].as_bool(),
                    Some(true),
                    "{name}: python said rejected ({:?}), rust filled",
                    expected["reject_reason"]
                );
                let exit = simulate_exit(&scenario, &exit_cfg, &fill);
                let record = TradeRecord::from_fill_and_exit(&scenario, &fill, &exit);

                assert_eq!(
                    expected["fill_t_ms"].as_u64(),
                    Some(fill.fill_t_ms),
                    "{name}: fill tick"
                );
                assert!(
                    close(fill.fill_price_sol, expected["fill_price_sol"].as_f64().unwrap()),
                    "{name}: fill price {} vs {}",
                    fill.fill_price_sol,
                    expected["fill_price_sol"]
                );
                assert!(
                    close(fill.cost_sol, expected["cost_sol"].as_f64().unwrap()),
                    "{name}: cost {} vs {}",
                    fill.cost_sol,
                    expected["cost_sol"]
                );
                assert!(
                    close(fill.tokens_bought, expected["tokens_bought"].as_f64().unwrap()),
                    "{name}: tokens"
                );
                assert!(
                    close(fill.filled_fraction, expected["filled_fraction"].as_f64().unwrap()),
                    "{name}: filled fraction"
                );
                assert!(
                    close(fill.impact_bps, expected["impact_bps"].as_f64().unwrap()),
                    "{name}: impact bps"
                );
                assert_eq!(
                    expected["exit_reason"].as_str(),
                    Some(exit.reason.as_str()),
                    "{name}: exit reason"
                );
                assert_eq!(
                    expected["exit_t_ms"].as_u64(),
                    Some(exit.exit_t_ms),
                    "{name}: exit tick"
                );
                assert!(
                    close(exit.exit_price_sol, expected["exit_price_sol"].as_f64().unwrap()),
                    "{name}: exit price"
                );
                assert!(
                    close(exit.gross_sol, expected["gross_sol"].as_f64().unwrap()),
                    "{name}: gross"
                );
                assert!(
                    close(exit.net_sol, expected["net_sol"].as_f64().unwrap()),
                    "{name}: net"
                );
                assert!(
                    close(record.pnl_sol, expected["pnl_sol"].as_f64().unwrap()),
                    "{name}: pnl"
                );
            }
        }
    }
}

#[test]
fn corpus_run_is_deterministic_and_labelled() {
    let fixtures = load_fixtures();
    let scenarios: Vec<BacktestScenario> = fixtures
        .iter()
        .map(|(_, v)| serde_json::from_value(v["scenario"].clone()).expect("scenario parses"))
        .collect();

    let fill_cfg = FillModelConfig::default();
    let exit_cfg = ExitConfig::default();

    let report_a = run_backtest(&scenarios, &fill_cfg, &exit_cfg);
    let report_b = run_backtest(&scenarios, &fill_cfg, &exit_cfg);
    assert_eq!(
        serde_json::to_string(&report_a).unwrap(),
        serde_json::to_string(&report_b).unwrap(),
        "backtest report must be byte-identical across runs"
    );

    assert_eq!(report_a.label, DatasetLabel::Synthetic);
    assert_eq!(report_a.scenarios, scenarios.len() as u64);
    assert_eq!(report_a.traded + report_a.missed, scenarios.len() as u64);
    assert!(report_a.model_caveats.iter().any(|c| c.contains("SYNTHETIC")));
    // Aggregate sanity against the reference outcomes: net PnL over the
    // default-config run must equal the sum of the per-scenario pnls the
    // same run reports (no hidden rounding between layers).
    let sum: f64 = report_a
        .per_scenario
        .iter()
        .map(|r| match &r.outcome {
            module_sniper::backtest::ScenarioOutcome::Traded { pnl_sol, .. } => *pnl_sol,
            module_sniper::backtest::ScenarioOutcome::Missed { .. } => 0.0,
        })
        .sum();
    assert!(
        close(report_a.metrics.net_pnl_sol, sum),
        "aggregate {} ≠ sum of rows {}",
        report_a.metrics.net_pnl_sol,
        sum
    );
}

#[test]
fn a_serialized_report_keeps_its_synthetic_label() {
    // The server stores this JSON as backtest_runs.result_json; the label
    // must survive a serde round trip so no consumer can lose it.
    let scenarios = module_sniper::backtest::dataset::synthetic_scenarios(2, 3);
    let report = run_backtest(
        &scenarios,
        &FillModelConfig::default(),
        &ExitConfig::default(),
    );
    let json = serde_json::to_string(&report).unwrap();
    assert!(json.contains("\"label\":\"synthetic\""));
    let back: module_sniper::backtest::BacktestReport = serde_json::from_str(&json).unwrap();
    assert_eq!(back, report);
}
