//! Deterministic replay (TASK 2 §M): recorded fixtures are driven through
//! the validation pipeline with no network and no submission, and every
//! step's outcome must match the expectation recorded in the fixture.
//!
//! Fixtures live in `crates/module-sniper/fixtures/replay/*.json`. They are
//! generated by [`regenerate_replay_fixtures`] (ignored by default; run with
//! `cargo test -p module-sniper --test replay -- --ignored regenerate`) so the
//! checked-in files and the generator never drift.

use std::path::PathBuf;

use chrono::{DateTime, Duration, TimeZone, Utc};
use solana_sdk::pubkey::Pubkey;

use bot_core::config::{AppConfig, Config, ExecutionConfig, RiskConfig, SniperConfig};
use bot_core::models::{LaunchFeed, TokenLaunch};
use bot_core::state::AppState;

use module_sniper::entry::entry_intent_id;
use module_sniper::event::{LaunchEvent, LaunchProtocol};
use module_sniper::gates::MarketSnapshot;
use module_sniper::pipeline::{EntryRoute, RejectReason, SniperStage};
use module_sniper::replay::{Expectation, ReplayEngine, ReplayFixture, ReplayStep};

const SOL: u64 = 1_000_000_000;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/replay")
}

fn t0() -> DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap()
}

fn key(seed: u8) -> Pubkey {
    Pubkey::new_from_array([seed; 32])
}

fn sig(seed: u8) -> String {
    let mut b = [0u8; 64];
    b[0] = seed;
    b[63] = seed.max(1);
    bs58::encode(b).into_string()
}

fn launch(mint_seed: u8, sig_seed: u8, observed_at: DateTime<Utc>) -> TokenLaunch {
    TokenLaunch {
        mint: key(mint_seed).to_string(),
        name: format!("Fixture {mint_seed}"),
        symbol: format!("FX{mint_seed}"),
        uri: None,
        creator: key(200).to_string(),
        pool: "bonding-curve".into(),
        initial_buy_sol: 0.5,
        market_cap_sol: 30.5,
        market_cap_usd: None,
        total_supply: Some(1_000_000_000.0),
        slot: Some(1_000 + mint_seed as u64),
        signature: Some(sig(sig_seed)),
        tx_type: Some("create".into()),
        observed_at,
        feed: LaunchFeed::PumpPortal,
        socials: None,
    }
}

fn pump_event(mint_seed: u8, sig_seed: u8, seq: u64) -> LaunchEvent {
    let mut ev = LaunchEvent::from_token_launch(
        launch(mint_seed, sig_seed, t0()),
        seq,
        format!("fixture-raw-{mint_seed}-{sig_seed}"),
    );
    ev.event_ts = Some(t0() - Duration::seconds(1));
    ev.event_id = ev.compute_event_id();
    ev
}

fn curve_snapshot() -> MarketSnapshot {
    MarketSnapshot {
        protocol: LaunchProtocol::PumpFun,
        pool: None,
        quote_reserve_lamports: SOL / 2,
        pricing_quote_reserve_lamports: 30 * SOL + SOL / 2,
        base_reserve_raw: 775_100_000_000_000,
        base_decimals: 6,
        total_supply_raw: Some(1_000_000_000_000_000),
        fee_bps: 100,
        tradable: true,
        tradable_detail: String::new(),
        pool_open_time: None,
        mint_authority_revoked: Some(true),
        freeze_authority_revoked: Some(true),
        creator_initial_buy_sol: Some(0.5),
        spot_price_sol: 2.9e-8,
        fetched_at: t0(),
    }
}

fn expect(stage: SniperStage, reason: Option<RejectReason>) -> Expectation {
    Expectation { stage, reason }
}

fn step(event: LaunchEvent, snapshot: Option<MarketSnapshot>, expect: Expectation) -> ReplayStep {
    ReplayStep {
        event,
        snapshot,
        curve_complete: false,
        now_offset_ms: 100,
        kill_switch: None,
        symbol_gated: None,
        emergency_disable: None,
        book_realized_sol: None,
        expect,
    }
}

fn base_sniper() -> SniperConfig {
    SniperConfig {
        buy_sol: 0.05,
        slippage_pct: 15.0,
        max_launch_age_secs: 30,
        max_entry_latency_ms: 0,
        ..SniperConfig::default()
    }
}

fn base_risk() -> RiskConfig {
    RiskConfig {
        min_creator_buy_sol: 0.0,
        min_socials: 0,
        max_launch_market_cap_sol: 0.0,
        sniper_max_pending_executions: 0,
        ..RiskConfig::default()
    }
}

fn fixture(name: &str, description: &str, steps: Vec<ReplayStep>) -> ReplayFixture {
    ReplayFixture {
        name: name.into(),
        description: description.into(),
        wallet_sol: 5.0,
        sniper: base_sniper(),
        risk: base_risk(),
        execution: None,
        steps,
    }
}

/// The canonical fixture set. Deterministic: fixed keys, signatures and
/// timestamps, so regenerating produces byte-identical files.
fn all_fixtures() -> Vec<ReplayFixture> {
    let mut out = Vec::new();

    out.push(fixture(
        "01_valid_launch",
        "A healthy pump.fun launch passes every check and reaches EXECUTION_READY with a deterministic intent id.",
        vec![step(
            pump_event(1, 1, 1),
            Some(curve_snapshot()),
            expect(SniperStage::ExecutionReady, None),
        )],
    ));

    out.push(fixture(
        "02_duplicate_event",
        "The same launch observed twice (second feed, later sequence): the second observation is a DUPLICATE_EVENT.",
        vec![
            step(
                pump_event(2, 2, 1),
                Some(curve_snapshot()),
                expect(SniperStage::ExecutionReady, None),
            ),
            step(
                pump_event(2, 2, 2),
                Some(curve_snapshot()),
                expect(SniperStage::Rejected, Some(RejectReason::DuplicateEvent)),
            ),
        ],
    ));

    {
        let mut s = step(
            pump_event(3, 3, 1),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::StaleEvent)),
        );
        s.now_offset_ms = 60_000;
        out.push(fixture(
            "03_stale_event",
            "Evaluated 60 s after observation with max_launch_age_secs = 30: STALE_EVENT before any market read.",
            vec![s],
        ));
    }

    {
        let mut forged = pump_event(4, 4, 1);
        forged.event_id = "evt_forged".into();
        let mut bad_sig = pump_event(4, 5, 2);
        bad_sig.signature = Some("not-base58-!!".into());
        bad_sig.event_id = bad_sig.compute_event_id();
        let mut no_pool = pump_event(4, 6, 3);
        no_pool.protocol = LaunchProtocol::PumpSwap;
        no_pool.pool = None;
        no_pool.event_id = no_pool.compute_event_id();
        out.push(fixture(
            "04_malformed_events",
            "A forged event id, a malformed signature and an AMM event without a pool are all INVALID_EVENT.",
            vec![
                step(forged, Some(curve_snapshot()), expect(SniperStage::Rejected, Some(RejectReason::InvalidEvent))),
                step(bad_sig, Some(curve_snapshot()), expect(SniperStage::Rejected, Some(RejectReason::InvalidEvent))),
                step(no_pool, Some(curve_snapshot()), expect(SniperStage::Rejected, Some(RejectReason::InvalidEvent))),
            ],
        ));
    }

    {
        let mut f = fixture(
            "05_insufficient_liquidity",
            "min_liquidity_sol = 2 against a curve holding 0.5 SOL: INSUFFICIENT_LIQUIDITY; a second launch with an empty pricing reserve fails the same gate.",
            vec![],
        );
        f.sniper.min_liquidity_sol = 2.0;
        let mut empty = curve_snapshot();
        empty.pricing_quote_reserve_lamports = 0;
        f.steps = vec![
            step(
                pump_event(5, 7, 1),
                Some(curve_snapshot()),
                expect(
                    SniperStage::Rejected,
                    Some(RejectReason::InsufficientLiquidity),
                ),
            ),
            step(
                pump_event(6, 8, 2),
                Some(empty),
                expect(
                    SniperStage::Rejected,
                    Some(RejectReason::InsufficientLiquidity),
                ),
            ),
        ];
        out.push(f);
    }

    {
        let mut f = fixture(
            "06_excessive_slippage",
            "price_impact mode with a 5 bps hard maximum: the modelled impact cannot fit → SLIPPAGE_LIMIT; then a 10 bps price-impact cap → PRICE_IMPACT_LIMIT.",
            vec![],
        );
        f.sniper.slippage_mode = "price_impact".into();
        f.risk.max_slippage_bps = 5;
        f.steps.push(step(
            pump_event(7, 9, 1),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::SlippageLimit)),
        ));
        out.push(f);

        let mut g = fixture(
            "06b_price_impact_limit",
            "max_price_impact_bps = 10 against a 0.05 SOL buy into 30.5 SOL (≈16 bps): PRICE_IMPACT_LIMIT.",
            vec![],
        );
        g.sniper.max_price_impact_bps = 10;
        g.steps.push(step(
            pump_event(8, 10, 1),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::PriceImpactLimit)),
        ));
        out.push(g);
    }

    {
        let mut f = fixture(
            "07_risk_rejection",
            "Wallet below the SOL reserve → RISK_REJECTED by the risk engine; kill switch → KILL_SWITCH; symbol gated → SYMBOL_GATED.",
            vec![],
        );
        f.wallet_sol = 0.01;
        let mut killed = step(
            pump_event(10, 12, 2),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::KillSwitch)),
        );
        killed.kill_switch = Some(true);
        let mut released = step(
            pump_event(11, 13, 3),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::SymbolGated)),
        );
        released.kill_switch = Some(false);
        released.symbol_gated = Some(true);
        f.steps = vec![
            step(
                pump_event(9, 11, 1),
                Some(curve_snapshot()),
                expect(SniperStage::Rejected, Some(RejectReason::RiskRejected)),
            ),
            killed,
            released,
        ];
        out.push(f);
    }

    out.push(fixture(
        "08_successful_intent",
        "Two independent launches both reach EXECUTION_READY; their intent ids differ and each equals entry_intent_id(event, route).",
        vec![
            step(pump_event(12, 14, 1), Some(curve_snapshot()), expect(SniperStage::ExecutionReady, None)),
            step(pump_event(13, 15, 2), Some(curve_snapshot()), expect(SniperStage::ExecutionReady, None)),
        ],
    ));

    out.push(fixture(
        "09_failed_execution",
        "The venue cannot be read (no snapshot): EXECUTION_UNAVAILABLE at VALIDATED; replay never builds or submits anything.",
        vec![step(
            pump_event(14, 16, 1),
            None,
            expect(SniperStage::Rejected, Some(RejectReason::ExecutionUnavailable)),
        )],
    ));

    {
        // Launch A at slot 1015, launch B at slot 1016 (seq 2), then A again
        // replayed after a reconnect at a lower sequence position.
        let a = pump_event(15, 17, 1);
        let b = pump_event(16, 18, 2);
        let mut a_again = pump_event(15, 17, 3);
        a_again.observed_at = t0() + Duration::seconds(2);
        a_again.launch.observed_at = a_again.observed_at;
        out.push(fixture(
            "10_reconnect_gap",
            "After a websocket gap the feed replays launch A: the replay is a DUPLICATE_EVENT; launch B (first seen after the gap) trades.",
            vec![
                step(a, Some(curve_snapshot()), expect(SniperStage::ExecutionReady, None)),
                step(b, Some(curve_snapshot()), expect(SniperStage::ExecutionReady, None)),
                step(a_again, Some(curve_snapshot()), expect(SniperStage::Rejected, Some(RejectReason::DuplicateEvent))),
            ],
        ));
    }

    {
        let mut ev = pump_event(17, 19, 1);
        ev.protocol = LaunchProtocol::PumpSwap;
        ev.pool = Some(key(150).to_string());
        ev.liquidity_quote_lamports = Some(85 * SOL);
        ev.liquidity_base_raw = Some(200_000_000_000_000);
        ev.event_id = ev.compute_event_id();
        let mut snap = curve_snapshot();
        snap.protocol = LaunchProtocol::PumpSwap;
        snap.pool = Some(key(150).to_string());
        snap.quote_reserve_lamports = 85 * SOL;
        snap.pricing_quote_reserve_lamports = 85 * SOL;
        snap.base_reserve_raw = 200_000_000_000_000;
        snap.spot_price_sol = 4.25e-7;
        let mut s = step(ev, Some(snap), expect(SniperStage::ExecutionReady, None));
        s.curve_complete = true;
        out.push(fixture(
            "11_pumpswap_launch",
            "A PumpSwap pool creation routes to the direct PumpSwap venue and reaches EXECUTION_READY.",
            vec![s],
        ));
    }

    {
        let mut ev = pump_event(18, 20, 1);
        ev.protocol = LaunchProtocol::RaydiumAmmV4;
        ev.pool = Some(key(151).to_string());
        ev.base_decimals = None;
        ev.event_id = ev.compute_event_id();
        let mut not_open = curve_snapshot();
        not_open.protocol = LaunchProtocol::RaydiumAmmV4;
        not_open.pool = Some(key(151).to_string());
        not_open.quote_reserve_lamports = 5 * SOL;
        not_open.pricing_quote_reserve_lamports = 5 * SOL;
        not_open.pool_open_time = Some((t0() + Duration::hours(1)).timestamp() as u64);
        let mut open = not_open.clone();
        open.pool_open_time = Some(0);
        let mut ev2 = pump_event(19, 21, 2);
        ev2.protocol = LaunchProtocol::RaydiumAmmV4;
        ev2.pool = Some(key(152).to_string());
        ev2.event_id = ev2.compute_event_id();
        open.pool = Some(key(152).to_string());
        out.push(fixture(
            "12_raydium_launch",
            "A Raydium pool whose open_time is in the future is POOL_NOT_READY; an open pool reaches EXECUTION_READY on the direct Raydium route.",
            vec![
                step(ev, Some(not_open), expect(SniperStage::Rejected, Some(RejectReason::PoolNotReady))),
                step(ev2, Some(open), expect(SniperStage::ExecutionReady, None)),
            ],
        ));
    }

    {
        let mut f = fixture(
            "13_token_state_and_concentration",
            "Freeze authority still set → TOKEN_STATE_INVALID; creator buy above the cap → CONCENTRATION_LIMIT; unknown mint state under strict_gates → TOKEN_STATE_INVALID.",
            vec![],
        );
        f.sniper.max_creator_initial_buy_sol = 0.4;
        let mut frozen = curve_snapshot();
        frozen.freeze_authority_revoked = Some(false);
        let ok_mint_big_buy = curve_snapshot(); // creator bought 0.5 > 0.4
        let mut unknown = curve_snapshot();
        unknown.creator_initial_buy_sol = Some(0.1);
        unknown.freeze_authority_revoked = None;
        f.steps = vec![
            step(
                pump_event(20, 22, 1),
                Some(frozen),
                expect(SniperStage::Rejected, Some(RejectReason::TokenStateInvalid)),
            ),
            step(
                pump_event(21, 23, 2),
                Some(ok_mint_big_buy),
                expect(
                    SniperStage::Rejected,
                    Some(RejectReason::ConcentrationLimit),
                ),
            ),
        ];
        out.push(f);

        let mut g = fixture(
            "13b_strict_gates",
            "strict_gates = true turns an unreadable mint (freeze state unknown) into TOKEN_STATE_INVALID.",
            vec![step(pump_event(22, 24, 1), Some(unknown), expect(SniperStage::Rejected, Some(RejectReason::TokenStateInvalid)))],
        );
        g.sniper.strict_gates = true;
        out.push(g);
    }

    {
        let mut f = fixture(
            "14_invalid_route",
            "A Raydium launch with trade_raydium and the Jupiter fallback both off is INVALID_ROUTE before any market read.",
            vec![],
        );
        f.sniper.trade_raydium = false;
        f.sniper.use_jupiter_fallback = false;
        let mut ev = pump_event(23, 25, 1);
        ev.protocol = LaunchProtocol::RaydiumAmmV4;
        ev.pool = Some(key(153).to_string());
        ev.event_id = ev.compute_event_id();
        f.steps.push(step(
            ev,
            None,
            expect(SniperStage::Rejected, Some(RejectReason::InvalidRoute)),
        ));
        out.push(f);
    }

    {
        let mut f = fixture(
            "15_strategy_disabled_and_exposure",
            "risk.sniper_emergency_disable → STRATEGY_DISABLED before any market data is read; once released, a fresh launch trades with sniper_max_concurrent_positions = 0 (0 = inherit the global cap); after −0.5 SOL of realised sniper loss against sniper_daily_loss_limit_quote = 0.5 the next launch is EXPOSURE_LIMIT.",
            vec![],
        );
        f.risk.sniper_max_concurrent_positions = 0;
        f.risk.sniper_daily_loss_limit_quote = 0.5;
        let mut disabled = step(
            pump_event(24, 26, 1),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::StrategyDisabled)),
        );
        disabled.emergency_disable = Some(true);
        let mut released = step(
            pump_event(25, 27, 2),
            Some(curve_snapshot()),
            expect(SniperStage::ExecutionReady, None),
        );
        released.emergency_disable = Some(false);
        let mut after_losses = step(
            pump_event(26, 28, 3),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::ExposureLimit)),
        );
        after_losses.book_realized_sol = Some(-0.5);
        f.steps = vec![disabled, released, after_losses];
        out.push(f);
    }

    {
        // Fee budget (check 15) priced from a pinned [execution] section so
        // the numbers do not depend on the engine's defaults: fixed policy,
        // 250 000 µlamports/CU × 400 000 CU, 2 attempts (+50% escalation)
        // → worst case 375 000 µlamports/CU → 150 000 + 5 000 base =
        // 155 000 lamports. A 120 000-lamport budget refuses it.
        let mut f = fixture(
            "16_fee_budget",
            "sniper.max_entry_fee_lamports = 120000 against a pinned [execution] section whose worst-case entry fee is 155000 lamports (5000 base + 375000 µlamports/CU × 400000 CU after one +50% retry) → FEE_LIMIT before risk; the same launch with the budget off is EXECUTION_READY.",
            vec![],
        );
        let pinned = ExecutionConfig {
            priority_fee_micro_lamports: 250_000,
            compute_unit_limit: 400_000,
            send_retries: 2,
            use_jito: false,
            fee_mode: "fixed".into(),
            fee_min_micro_lamports: 0,
            fee_max_micro_lamports: 5_000_000,
            fee_emergency_max_micro_lamports: 20_000_000,
            fee_escalation_pct: 50,
            ..ExecutionConfig::default()
        };
        f.execution = Some(pinned.clone());
        f.sniper.max_entry_fee_lamports = 120_000;
        f.steps.push(step(
            pump_event(27, 29, 1),
            Some(curve_snapshot()),
            expect(SniperStage::Rejected, Some(RejectReason::FeeLimit)),
        ));
        out.push(f);

        let mut g = fixture(
            "16b_fee_budget_off",
            "The same launch and [execution] section with sniper.max_entry_fee_lamports = 0 (no budget): the fee policy accepts the configured priority fee and the launch is EXECUTION_READY.",
            vec![],
        );
        g.execution = Some(pinned);
        g.sniper.max_entry_fee_lamports = 0;
        g.steps.push(step(
            pump_event(28, 30, 1),
            Some(curve_snapshot()),
            expect(SniperStage::ExecutionReady, None),
        ));
        out.push(g);
    }

    out
}

fn fresh_engine() -> ReplayEngine {
    let mut cfg = Config::default();
    cfg.sniper.enabled = true;
    ReplayEngine::new(AppState::new(AppConfig {
        raw: cfg,
        source_path: None,
        warnings: Vec::new(),
    }))
}

#[test]
#[ignore = "writes the fixture files; run explicitly after changing the generator"]
fn regenerate_replay_fixtures() {
    let dir = fixtures_dir();
    std::fs::create_dir_all(&dir).unwrap();
    for f in all_fixtures() {
        let path = dir.join(format!("{}.json", f.name));
        std::fs::write(&path, f.to_json().unwrap()).unwrap();
    }
}

#[tokio::test]
async fn checked_in_fixtures_match_the_generator() {
    // The files on disk must be exactly what the generator produces, so a
    // change to either side is caught here rather than silently drifting.
    let on_disk = ReplayFixture::load_dir(&fixtures_dir()).expect("fixtures dir");
    let generated = all_fixtures();
    assert_eq!(on_disk.len(), generated.len(), "fixture count");
    for (g, (name, d)) in generated.iter().zip(on_disk.iter()) {
        assert_eq!(&g.name, name);
        assert_eq!(
            g.to_json().unwrap(),
            d.to_json().unwrap(),
            "fixture {name} drifted"
        );
    }
}

#[tokio::test]
async fn every_fixture_replays_to_its_recorded_outcome() {
    let fixtures = ReplayFixture::load_dir(&fixtures_dir()).expect("fixtures dir");
    assert!(
        fixtures.len() >= 15,
        "expected the full fixture set, got {}",
        fixtures.len()
    );
    for (name, fixture) in fixtures {
        let engine = fresh_engine();
        let report = engine.run(&fixture).await;
        assert!(
            report.all_matched(),
            "fixture {name} mismatched:\n{}",
            report.render()
        );
        // Successful steps carry the exact live intent id and a route.
        for o in &report.outcomes {
            if o.stage == SniperStage::ExecutionReady {
                let event = &fixture.steps[o.step].event;
                assert_eq!(o.intent_id, entry_intent_id(event, o.route.unwrap()));
                assert!(o.slippage_bps.is_some() && o.sized_sol.is_some());
                assert!(
                    o.fee_estimate_lamports.is_some_and(|f| f >= 5_000),
                    "every approved step was fee-budgeted: {o:?}"
                );
                assert!(
                    o.path.ends_with("VALIDATED>RISK_APPROVED>EXECUTION_READY"),
                    "{}",
                    o.path
                );
            }
        }
    }
}

#[tokio::test]
async fn replay_is_deterministic_and_never_touches_the_ledger() {
    let fixtures = ReplayFixture::load_dir(&fixtures_dir()).unwrap();
    let (_, valid) = fixtures
        .iter()
        .find(|(n, _)| n == "08_successful_intent")
        .unwrap()
        .clone();
    let a = fresh_engine().run(&valid).await;
    let b = fresh_engine().run(&valid).await;
    assert_eq!(
        serde_json::to_string(&a.outcomes).unwrap(),
        serde_json::to_string(&b.outcomes).unwrap(),
        "two runs, identical outcomes"
    );
    let ids: Vec<_> = a
        .outcomes
        .iter()
        .filter_map(|o| o.intent_id.clone())
        .collect();
    assert_eq!(ids.len(), 2);
    assert_ne!(ids[0], ids[1]);
    // Nothing reached the execution ledger: replay cannot submit.
    let records = bot_core::execution::ledger().list(10_000).await;
    for step in &valid.steps {
        assert!(
            !records.iter().any(|r| r.symbol == step.event.mint),
            "replay must never create ledger records"
        );
    }
    // Report rendering names the would-be submission.
    let text = a.render();
    assert!(text.contains("would submit intent int_"), "{text}");
    assert!(text.contains("OK"));
}

#[tokio::test]
async fn routes_in_the_amm_fixtures_are_the_direct_venues() {
    let fixtures = ReplayFixture::load_dir(&fixtures_dir()).unwrap();
    let ps = &fixtures
        .iter()
        .find(|(n, _)| n == "11_pumpswap_launch")
        .unwrap()
        .1;
    let r = fresh_engine().run(ps).await;
    assert_eq!(
        r.outcomes[0].route,
        Some(EntryRoute::PumpSwapDirect),
        "{}",
        r.render()
    );
    let ray = &fixtures
        .iter()
        .find(|(n, _)| n == "12_raydium_launch")
        .unwrap()
        .1;
    let r = fresh_engine().run(ray).await;
    assert_eq!(
        r.outcomes[1].route,
        Some(EntryRoute::RaydiumV4Direct),
        "{}",
        r.render()
    );
    assert_eq!(
        r.outcomes[0].rejection.as_ref().map(|x| x.reason),
        Some(RejectReason::PoolNotReady)
    );
}

#[test]
fn fixture_json_round_trips_and_rejects_garbage() {
    let f = all_fixtures().remove(0);
    let json = f.to_json().unwrap();
    let back = ReplayFixture::from_json(&json).unwrap();
    assert_eq!(back.name, f.name);
    assert_eq!(back.steps.len(), 1);
    assert!(ReplayFixture::from_json("{not json").is_err());
    assert!(ReplayFixture::load(&fixtures_dir().join("does-not-exist.json")).is_err());
}
