//! Deterministic backtesting for the sniper entry/exit policy
//! (GAP-MAP P1 NEW).
//!
//! ## Honesty rules this module is built around
//!
//! 1. **Every dataset is labelled.** [`DatasetLabel`] is serialized into
//!    every scenario and every [`BacktestReport`]. The only label that
//!    exists today is [`DatasetLabel::Synthetic`]: all bundled fixtures are
//!    generated by a seeded PRNG and say so in their file name, their JSON
//!    and their report. Nothing here may ever present a synthetic number
//!    as real launch performance.
//! 2. **No hidden randomness.** The fill model, the exit simulator and the
//!    metrics are pure functions of (scenario, config). Running the same
//!    input twice yields a byte-identical report; `backtest_golden.rs`
//!    pins that property.
//! 3. **The models are conservative and say what they ignore.** The fill
//!    model assumes you are price-taker at the post-latency tick plus a
//!    reserve-based impact term; it does NOT model queue position, MEV
//!    competition or leader schedules. Reports carry those caveats in
//!    [`BacktestReport::model_caveats`].
//!
//! The server-side `backtest_worker` (GAP-MAP P1, Part 4) runs this
//! simulator inside `spawn_blocking` and stores the resulting
//! [`BacktestReport`] as authoritative `result_json`.

pub mod dataset;
pub mod exit_sim;
pub mod fill_model;
pub mod metrics;

pub use dataset::{BacktestScenario, DatasetLabel, Tick};
pub use exit_sim::{simulate_exit, ExitConfig, ExitOutcome, ExitReason};
pub use fill_model::{simulate_fill, FillModelConfig, FillOutcome, FillReject};
pub use metrics::{compute_metrics, BacktestMetrics, TradeRecord};

use serde::{Deserialize, Serialize};

/// Run the full pipeline over a set of scenarios: fill → exit → record →
/// aggregate. Pure and deterministic.
pub fn run_backtest(
    scenarios: &[BacktestScenario],
    fill_cfg: &FillModelConfig,
    exit_cfg: &ExitConfig,
) -> BacktestReport {
    let mut trades: Vec<TradeRecord> = Vec::new();
    let mut misses: u64 = 0;
    let mut per_scenario = Vec::with_capacity(scenarios.len());

    for scenario in scenarios {
        let outcome = simulate_fill(scenario, fill_cfg);
        let detail = match outcome {
            FillOutcome::Filled(fill) => {
                let exit = simulate_exit(scenario, exit_cfg, &fill);
                let record = TradeRecord::from_fill_and_exit(scenario, &fill, &exit);
                let pnl = record.pnl_sol;
                trades.push(record);
                ScenarioOutcome::Traded {
                    exit_reason: exit.reason.as_str().to_string(),
                    pnl_sol: pnl,
                }
            }
            FillOutcome::Rejected(reject) => {
                misses += 1;
                ScenarioOutcome::Missed {
                    reason: reject.as_str().to_string(),
                }
            }
        };
        per_scenario.push(ScenarioOutcomeEntry {
            name: scenario.name.clone(),
            outcome: detail,
        });
    }

    // Sort by scenario name so the aggregate is independent of input
    // order (fixtures load in directory order; this pins the sum order).
    per_scenario.sort_by(|a, b| a.name.cmp(&b.name));
    trades.sort_by(|a, b| a.scenario.cmp(&b.scenario));

    BacktestReport {
        label: DatasetLabel::Synthetic,
        scenarios: scenarios.len() as u64,
        traded: trades.len() as u64,
        missed: misses,
        metrics: compute_metrics(&trades),
        per_scenario,
        model_caveats: vec![
            "all bundled scenarios are SYNTHETIC (seeded PRNG), not real launch data".into(),
            "fill model is price-taker at the post-latency tick; no queue-position or MEV model".into(),
            "landing uses a congestion threshold, not leader/block-engine simulation".into(),
        ],
    }
}

/// One scenario's fate inside a [`BacktestReport`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ScenarioOutcome {
    /// The fill model executed and the exit simulator closed the trade.
    Traded { exit_reason: String, pnl_sol: f64 },
    /// The entry never happened (latency budget, congestion, empty path).
    Missed { reason: String },
}

/// Per-scenario result row.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScenarioOutcomeEntry {
    pub name: String,
    pub outcome: ScenarioOutcome,
}

/// The aggregate result of one backtest run. Serialized to
/// `backtest_runs.result_json` by the server worker; the `label` field is
/// what the UI must surface ("synthetic data — not live results").
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BacktestReport {
    /// Always [`DatasetLabel::Synthetic`] while no real dataset pipeline
    /// exists. Anything presenting these numbers must show this label.
    pub label: DatasetLabel,
    /// Number of scenarios fed in.
    pub scenarios: u64,
    /// Scenarios where the entry filled.
    pub traded: u64,
    /// Scenarios where the entry was rejected (misses).
    pub missed: u64,
    /// Aggregate performance over the trades.
    pub metrics: BacktestMetrics,
    /// Deterministically ordered (by scenario name) per-scenario rows.
    pub per_scenario: Vec<ScenarioOutcomeEntry>,
    /// What the models do NOT capture. Must be displayed with the numbers.
    pub model_caveats: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backtest::dataset::synthetic_scenarios;

    #[test]
    fn run_backtest_is_deterministic_and_labelled() {
        let scenarios = synthetic_scenarios(42, 8);
        let fill_cfg = FillModelConfig::default();
        let exit_cfg = ExitConfig::default();
        let a = run_backtest(&scenarios, &fill_cfg, &exit_cfg);
        let b = run_backtest(&scenarios, &fill_cfg, &exit_cfg);
        assert_eq!(
            serde_json::to_string(&a).unwrap(),
            serde_json::to_string(&b).unwrap(),
            "same input must give byte-identical reports"
        );
        assert_eq!(a.label, DatasetLabel::Synthetic);
        assert_eq!(a.scenarios, 8);
        assert_eq!(a.traded + a.missed, 8);
        assert!(!a.model_caveats.is_empty());
        // Rows are ordered by scenario name regardless of input order.
        let names: Vec<&str> = a.per_scenario.iter().map(|r| r.name.as_str()).collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted);
    }

    #[test]
    fn input_order_does_not_change_the_aggregate() {
        let mut scenarios = synthetic_scenarios(7, 6);
        let fill_cfg = FillModelConfig::default();
        let exit_cfg = ExitConfig::default();
        let forward = run_backtest(&scenarios, &fill_cfg, &exit_cfg);
        scenarios.reverse();
        let backward = run_backtest(&scenarios, &fill_cfg, &exit_cfg);
        assert_eq!(forward.metrics, backward.metrics);
        assert_eq!(forward.per_scenario, backward.per_scenario);
    }
}
