-- 0040_durable_report_exports.sql — tenant-scoped generated report artifacts.
--
-- Report metadata and the generated bytes are durable. The application only
-- writes content assembled from tenant-owned authoritative rows; it never
-- inserts sample report metadata or sample trade rows.

CREATE TABLE IF NOT EXISTS report_exports (
    id              uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name            text NOT NULL,
    report_type     text NOT NULL CHECK (report_type IN ('accounting_ledger', 'execution_journal', 'security_audit', 'risk_events', 'custody_rotation')),
    format          text NOT NULL CHECK (format IN ('csv', 'json')),
    date_from       timestamptz NOT NULL,
    date_to         timestamptz NOT NULL,
    content_type    text NOT NULL,
    CONSTRAINT report_exports_valid_window CHECK (date_to >= date_from),
    content        bytea NOT NULL,
    record_count    bigint NOT NULL CHECK (record_count >= 0),
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS report_exports_org_created_idx
    ON report_exports (organization_id, created_at DESC, id DESC);
