#!/usr/bin/env bash
# tests/release/manifest_current.sh — the release manifest must describe
# the tree as it is NOW (PROMPT 6 §J).
#
# The manifest's measurable fields are regenerated by
# scripts/update-release-manifest.sh; this test recomputes them
# independently and refuses to let a stale manifest ship:
#   * docs_files   — every .md in docs/
#   * rust_files   — every .rs under crates/
#   * migrations   — count + high-water of crates/core/migrations
#   * version      — VERSION file = manifest product.version
# A manifest that disagrees with the tree is a stale-number defect,
# exactly the class PROMPT 6 §P9 exists to eliminate.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
MANIFEST="$ROOT/release-manifest.json"
FAIL=0

if [ ! -f "$MANIFEST" ]; then
  echo "[manifest-current] FAIL — $MANIFEST missing" >&2
  exit 1
fi

DOCS_REAL="$(ls "$ROOT"/docs/*.md 2>/dev/null | wc -l | tr -d ' ')"
RUST_REAL="$(find "$ROOT/crates" -type f -name '*.rs' | wc -l | tr -d ' ')"
MIG_REAL="$(ls "$ROOT"/crates/core/migrations/*.sql 2>/dev/null | wc -l | tr -d ' ')"
MIG_HIGH="$(ls "$ROOT"/crates/core/migrations/ | sed 's/_.*//' | sort | tail -1)"
VERSION_REAL="$(cat "$ROOT/VERSION")"

check() { # name actual manifest-value
  local name="$1" actual="$2" mval="$3"
  if [ "$actual" != "$mval" ]; then
    echo "[manifest-current] FAIL — $name: tree says '$actual', manifest says '$mval' — run scripts/update-release-manifest.sh" >&2
    FAIL=1
  else
    echo "[manifest-current] $name: OK ($actual)"
  fi
}

check "docs_files"    "$DOCS_REAL"  "$(python3 -c "import json;print(json.load(open('$MANIFEST'))['docs_files'])")"
check "rust_files"    "$RUST_REAL"  "$(python3 -c "import json;print(json.load(open('$MANIFEST'))['rust_files'])")"
check "migrations"    "$MIG_REAL"   "$(python3 -c "import json;print(json.load(open('$MANIFEST'))['migrations'])")"
check "migration high-water" "$MIG_HIGH" "$(python3 -c "import json;print(json.load(open('$MANIFEST'))['components']['database_migrations']['high_water_mark'])")"
check "version"       "$VERSION_REAL" "$(python3 -c "import json;print(json.load(open('$MANIFEST'))['version'])")"

if [ "$FAIL" -ne 0 ]; then
  echo "[manifest-current] FAIL — the manifest is stale" >&2
  exit 1
fi
echo "[manifest-current] PASS — manifest matches the tree"
exit 0
