#!/usr/bin/env bash
# ============================================================================
# scripts/pin-base-image-digests.sh — resolve every base image tag to an
# immutable digest and write deploy/release/base-images.lock.json (P0 §7).
#
# WHY
# ---
# A tag is a mutable pointer. `postgres:16-alpine` today and
# `postgres:16-alpine` next month are different images, so a "redeploy
# the same version" is not reproducible and a rollback does not
# necessarily roll anything back. A digest IS the image: byte-identical,
# forever, verifiable offline.
#
# This script talks to the registry HTTP API directly (no Docker daemon
# required, so it runs in CI and on a laptop alike) and records what each
# tag resolved to, when, and for which platform.
#
# Usage:
#   ./scripts/pin-base-image-digests.sh            # refresh the lock file
#   ./scripts/pin-base-image-digests.sh --check    # fail if it is stale
#
# After refreshing, update the `image:` lines that carry these digests:
#   Dockerfile, docker-compose.yml, deploy/compose/*.yml
# `scripts/verify-image-digests.sh` fails the build if they drift apart.
# ============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

LOCK="deploy/release/base-images.lock.json"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# Every base image this deployment pulls, as `repository:tag`. Keep this
# list in sync with the FROM / image: lines across the repo; the verify
# script cross-checks both directions.
IMAGES=(
    "postgres:16-alpine"
    "redis:7-alpine"
    "nginx:1.27-alpine"
    "rust:1.98.1-bookworm"
    "debian:bookworm-slim"
    "certbot/certbot:v3.1.0"
    "node:22-bookworm-slim"
)

ACCEPT='application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json'

resolve_digest() {
    local ref="$1" repo tag path token digest
    repo="${ref%:*}"
    tag="${ref##*:}"
    # Docker Hub official images live under the implicit `library/` namespace.
    case "$repo" in */*) path="$repo" ;; *) path="library/$repo" ;; esac

    token="$(curl -fsS "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${path}:pull" \
             | sed -E 's/.*"token":"([^"]+)".*/\1/')"
    [[ -n "$token" ]] || { echo "could not obtain a pull token for $path" >&2; return 1; }

    # The digest is in the response HEADER, not the body: the body is the
    # manifest, and hashing it locally would have to reproduce the
    # registry's exact canonical form. HEAD is cheap and authoritative.
    digest="$(curl -fsS -I -H "Authorization: Bearer $token" -H "Accept: $ACCEPT" \
              "https://registry-1.docker.io/v2/${path}/manifests/${tag}" \
              | tr -d '\r' | awk 'tolower($1)=="docker-content-digest:"{print $2}')"
    [[ "$digest" == sha256:* ]] || { echo "no digest returned for $ref" >&2; return 1; }
    printf '%s' "$digest"
}

mkdir -p "$(dirname "$LOCK")"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    printf '{\n'
    printf '  "comment": "Generated by scripts/pin-base-image-digests.sh. Do not hand-edit: run the script. A tag is a mutable pointer; the digest is the image.",\n'
    printf '  "generated_at": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '  "registry": "registry-1.docker.io",\n'
    printf '  "note_multi_arch": "Each digest is the MULTI-PLATFORM index digest where the tag publishes one, so the same pin is correct on amd64 and arm64.",\n'
    printf '  "images": {\n'
    last=$(( ${#IMAGES[@]} - 1 ))
    for i in "${!IMAGES[@]}"; do
        ref="${IMAGES[$i]}"
        echo "resolving $ref …" >&2
        d="$(resolve_digest "$ref")"
        comma=","
        [[ "$i" -eq "$last" ]] && comma=""
        printf '    "%s": {\n' "$ref"
        printf '      "digest": "%s",\n' "$d"
        printf '      "pinned_reference": "%s@%s"\n' "${ref%:*}" "$d"
        printf '    }%s\n' "$comma"
    done
    printf '  }\n'
    printf '}\n'
} > "$tmp"

if [[ "$CHECK" -eq 1 ]]; then
    [[ -f "$LOCK" ]] || { echo "FAIL: $LOCK does not exist — run $0" >&2; exit 1; }
    # Compare DIGESTS only: generated_at always differs.
    a="$(grep -o '"digest": "sha256:[a-f0-9]*"' "$LOCK" | sort)"
    b="$(grep -o '"digest": "sha256:[a-f0-9]*"' "$tmp" | sort)"
    if [[ "$a" != "$b" ]]; then
        echo "FAIL: $LOCK is stale — an upstream tag now resolves to a different image." >&2
        echo "      This is expected when a base image is rebuilt (security patches)." >&2
        echo "      Review the change, then run: $0" >&2
        diff <(echo "$a") <(echo "$b") || true
        exit 1
    fi
    echo "base image digests are current"
    exit 0
fi

mv "$tmp" "$LOCK"
trap - EXIT
echo
echo "wrote $LOCK"
echo "Now update the image references that use these digests, then run:"
echo "  ./scripts/verify-image-digests.sh"
